name: reuse-whoami

on:
  workflow_dispatch:

jobs:
  
  call-whoami:
    uses: devkeydet/pva-alm/.github/workflows/whoami.yml@main
    secrets:      
      environment_url: ${{ secrets.UAT_ENV }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}