name: checks-test #updates

on:
  pull_request:
    
jobs:
  checks-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: gh-script
      #   id: gh-script
      #   uses: actions/github-script@v5
      #   with:          
      #     # details_url cannot be set with the default GITHUB_TOKEN 
      #     github-token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }} 
      #     result-encoding: string
      #     script: |
      #       var checkResult = await github.rest.checks.create({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         head_sha: context.payload.pull_request.head.sha,
      #         name: "test name",
      #         status: "queued",
      #         details_url: "https://microsoft.com"
      #       })     

      #       return checkResult.data.id
      - name: gh-script
        id: gh-script
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            var checkResult = await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              context: "test-one",
              state: "pending"
            })     
            var checkResult = await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              context: "test-two",
              state: "pending"
            })

      # - name: Get result id
      #   run: |
      #     echo "check id: ${{steps.gh-script.outputs.result}}"
            