name: checks-test

on:
  pull_request:
    
jobs:
  checks-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: add-check
        name: add-check
        uses: LouisBrunner/checks-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: devkeydet-test-check
          status: queued
          details_url: https://www.microsoft.com
      - name: echo-check-id
        run: |
          echo "check_id: ${{ steps.add-check.outputs.check_id }}"
 