name: checks-test #updates

on:
  pull_request:
    
jobs:
  checks-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - id: add-check
      #   name: add-check
      #   uses: LouisBrunner/checks-action@v1.2.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     name: devkeydet-test-check
      #     status: queued
      #     details_url: https://www.microsoft.com
      # - name: echo-check-id
      #   run: |
      #     echo "check_id: ${{ steps.add-check.outputs.check_id }}"
      # - name: add-check-pwsh
      #   shell: pwsh
      #   run: |
      #     curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/check-runs -d '{"name":"pwsh","head_sha":"${{ github.sha }}"}'
      - name: gh-script
        id: gh-script
        uses: actions/github-script@v5
        with:
          #github-token: ${{ github.token }}
          result-encoding: string
          script: |
            let result = 0;
            const numbers = [65, 44, 12, 4];
            numbers.forEach(myFunction);

            function myFunction(item) {
              result += item;
            }           

            // return result

            var result = await github.rest.checks.create({              
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "test name",
              sha: ${{ github.sha }}
              status: "queued",
              details_url: "https://devkeydet.blog"
            })
      - name: Get result
        run: |
          echo "sum: ${{steps.gh-script.outputs.result}}"
            