name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'name of the Solution in Dataverse environment'
        required: true
        default: pvaalm
      environment_url:
        description: 'http endpoint of your Dataverse environment'
        required: true
        default: 'https://[your-env].crm.dynamics.com'
      solution_exported_folder:
        description: 'folder name for staging the exported solution'
        required: true
        default: out/exported-temp/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in'
        required: true
        default: out/unpack-temp/
      source_branch:
        description: 'source branch'
        required: true
        default: main
      branch_to_create:
        description: 'branch to create'
        required: true
        default: username-issuenumber

jobs:
  export-from-dev:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.source_branch }}
    
    - name: create new git branch
      run: |
        git checkout origin/${{ github.event.inputs.source_branch }} --track
        git checkout -b ${{ github.event.inputs.source_branch }} ${{ github.event.inputs.branch_to_create }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@0.4.3
      with:
        environment-url: ${{ github.event.inputs.environment_url}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{secrets.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@0.4.3
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: src/${{ github.event.inputs.solution_name }}/SolutionPackage
        solution-type: 'Unmanaged'
        overwrite-files: true  
