name: gh-call-workflow

on:
  workflow_dispatch:
  
permissions:
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: call another workflow
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }} 
          #GITHUB_TOKEN: ${{ GITHUB_TOKEN }} 
        run: |
          gh workflow run gh-test
