name: pr-pvaalm-main-build
# Run a build and validate deployment on pull request

on:
  pull_request:
    branches:
      - main
    paths:
      - src/pvaalm/**

jobs:
  build-deploy-pr-validation:
    runs-on: ubuntu-latest

    env:
      solution_name: pvaalm
      solution_pack_folder: solution-pack-temp

    steps:
      - uses: actions/checkout@v2

      - name: pack solution
        uses: microsoft/powerplatform-actions/pack-solution@0.4.3
        with:
          solution-folder: src/${{ env.solution_name }}/SolutionPackage
          solution-file: ${{ runner.temp }}/${{ env.solution_pack_folder }}/${{ env.solution_name }}.zip
          solution-type: Managed