name: pvaalm-pr-build-deploy

on:
  pull_request:
    branches:
      - main
    paths:
      - src/pvaalm/**

env:
  solution_name: pvaalm
  
jobs:
  build-solution:
    uses: devkeydet/pva-alm/.github/workflows/build-solution.yml@main
    with:
      solution_name: ${{ env.solution_name }}
  
  deploy-solution:
    uses: devkeydet/pva-alm/.github/workflows/deploy-solution.yml@main
    needs: build-solution
    with:
      solution_name: ${{ env.solution_name }}
    secrets:      
      ENVIRONMENT_URL: ${{ secrets.UAT_ENV }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}