name: pvaalm-pr-main-build-deploy
# Run a build and validate deployment on pull request
#

on:
  pull_request:
    branches:
      - main
    paths:
      - src/pvaalm/**
  push:
    branches:
      - main
    paths:
      - src/pvaalm/**

jobs:
  build-solution:
    uses: devkeydet/pva-alm/tree/main/.github/workflows/build-solution@main
    with:
      solution_name: pvaalm
  
  deploy-solution:
    uses: devkeydet/pva-alm/tree/main/.github/workflows/deploy-solution@main
    with:
      solution_name: pvaalm