name: pwsh-set-environment-variable
on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - id: my-step
        shell: pwsh
        run: echo "::set-output name=my_output::foo"        
      - shell: pwsh
        run: |
          echo "my_env=${{ steps.my-step.outputs.my_output  }}" >> $GITHUB_ENVshell: pwsh
      - run: echo "${{ env.my_env }}"
