# This is a basic workflow to help you get started with Actions

name: t

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  call:
    uses: devkeydet/pva-alm/.github/workflows/rt.yml@main
    secrets:
      secrets: ${{ toJSON(secrets) }}
