name: use-reusable-whoami

on:
  workflow_dispatch:

jobs:

  set-env-var-conditionally:
    runs-on: ubuntu-latest
    steps:
      - name: set environment variables conditionally
        shell: pwsh
        run: |
          $ref = '${{ github.ref }}'
          switch ( $ref )
          {
            'refs/heads/main'
            {
              echo 'refs/heads/main'
              echo 'environment_url=uat' | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
            }
            default
            {
              echo 'environment_url=pr' | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
            } 
          }
  echo-env-var-set:
    runs-on: ubuntu-latest
    needs: set-env-var-conditionally
    steps:
      - name: echo env var set
        run: |
          echo '${{ env.environment_url }}'

  call-whoami:
    uses: devkeydet/pva-alm/.github/workflows/reusable-whoami.yml@main
    needs: echo-env-var-set
    secrets:      
      environment_url: ${{ secrets.UAT_ENV }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}