name: use-reusable-whoami

on:
  workflow_dispatch:

concurrency: test

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello world'

  call-whoami:
    uses: devkeydet/pva-alm/.github/workflows/reusable-whoami.yml@main
    secrets:      
      environment_url: ${{ secrets.UAT_ENV }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}