name: use-reusable-whoami

on:
  workflow_dispatch:

jobs:

  set-env-var-conditionally:
    runs-on: ubuntu-latest
    
    steps: 
      - name: uat env var
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          echo "environment=uat" >> $GITHUB_ENV
      - name: pr env var
        if: startsWith(github.ref, 'refs/heads/main') == false
        run: |
          echo "environment=pr" >> $GITHUB_ENV
      - id: setOuput
        run: |
          echo "::set-output name=env::${{ env.environment }}"
    
    outputs:
      environment: ${{ steps.setOuput.outputs.env }}

  call-whoami-uat:
    uses: devkeydet/pva-alm/.github/workflows/reusable-whoami.yml@main
    needs: set-env-var-conditionally
    if: startsWith(github.ref, 'refs/heads/main')
    with: 
      environment: uat
    secrets:      
      environment_url: ${{ secrets.UAT_ENV }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
  
  call-whoami-pr:
    uses: devkeydet/pva-alm/.github/workflows/reusable-whoami.yml@main
    if: startsWith(github.ref, 'refs/heads/main') == false
    needs: set-env-var-conditionally
    with: 
      environment: pr
    secrets:      
      environment_url: ${{ secrets.ENVIRONMENT_URL }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}